# Generated by Django 3.1.7 on 2021-06-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Reponse',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
