# Generated by Django 3.1.7 on 2021-06-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210620_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Reponse',
            field=models.CharField(default='', max_length=80),
        ),
    ]
