# Generated by Django 3.1.7 on 2021-06-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210620_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Reponse',
            field=models.CharField(max_length=80),
        ),
    ]
