# Generated by Django 3.1.7 on 2021-06-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210620_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_responded',
            field=models.BooleanField(default=False),
        ),
    ]
