# Generated by Django 3.1.6 on 2023-01-03 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=30)),
                ('TypeLogement', models.CharField(max_length=50)),
                ('NombreChambre', models.IntegerField()),
                ('Surface', models.IntegerField()),
                ('Emplacement', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='annonce/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('NumTel', models.IntegerField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('prix', models.IntegerField(default=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonce', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
