# Generated by Django 3.1.6 on 2021-03-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='topic',
            name='distance',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='nombrechambre',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='topic',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='topic',
            name='surface',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='typee',
            field=models.CharField(default='', max_length=20),
        ),
    ]
