# Generated by Django 3.1.6 on 2021-03-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20210305_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default='DEFAULT VALUE', max_length=4000),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='DEFAULT VALUE', max_length=4000),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
