# Generated by Django 3.1.7 on 2021-03-17 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_annonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='created_by',
        ),
    ]
