# Generated by Django 3.1.7 on 2021-03-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0012_annonce_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
