# Generated by Django 3.1.7 on 2021-03-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0014_annonce_numtel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
