# Generated by Django 3.1.7 on 2021-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0016_auto_20210324_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='Title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
