# Generated by Django 3.1.6 on 2021-03-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0017_annonce_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='NombreChambre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='Surface',
            field=models.IntegerField(),
        ),
    ]
