# Generated by Django 3.1.7 on 2021-03-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0018_auto_20210331_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='board',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_by',
        ),
        migrations.AddField(
            model_name='annonce',
            name='prix',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
